apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
    name: redhat-na-ssa #REPLACE by the name of your Github Org
    namespace: vault-admin
spec:
  authentication: 
    path: dev-cluster-admin
    role: vault-admin
    serviceAccount:
      name: default
  path: github
  organizationName: "REPLACE-ME!!!"
  repositories: []
  permissions: 
    pull_requests: write
    metadata: read
    contents: write
    repository_hooks: write