apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuaySecretEngineRole
metadata:
  name: redhat_na_ssa
  namespace: vault-admin
spec:
  authentication: 
    path: dev-cluster-admin
    role: vault-admin
    serviceAccount:
      name: default
  path: quay
  namespaceName: "redhat-na-ssa"
  createRepositories: true
  defaultPermission: write
  TTL: "768h" #32 days (TTL capped by Vault)
  