apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  # name: openshift-cert-manager-operator
  # namespace: cert-manager-operator
  name: cert-manager
  namespace: openshift-operators
spec:
  # channel: stable-v1
  # installPlanApproval: Automatic
  # name: openshift-cert-manager-operator
  # source: redhat-operators
  # sourceNamespace: openshift-marketplace
  # startingCSV: cert-manager-operator.v1.12.1
  channel: stable
  installPlanApproval: Automatic
  name: cert-manager
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cert-manager.v1.13.1