apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      certmanager-issuer:
        email: {{ .Values.certmanager.issuer.email }}
      configureCertmanager:
        install: false
      global:
        hosts:
          domain: example.com # does't work on ArgoCD yet {{ (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain }}
        ingress:
          annotations:
            route.openshift.io/termination: edge
          class: none
          configureCertmanager: true
      nginx-ingress:
        enabled: false
