apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
  annotations:
    "helm.sh/hook-weight": "-5"
spec:
  upgradeStrategy: Default
  targetNamespaces:
  - cert-manager-operator