apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/vault-config/

patches:
  - patch: |-
      - op: replace
        path: /spec/applicationID
        value: 401106
    target:
      kind: GitHubSecretEngineConfig
  - patch: |-
      - op: replace
        path: /spec/organizationName
        value: "redhat-na-ssa"
    target:
      kind: GitHubSecretEngineRole
  - patch: |-
      - op: replace
        path: /spec/url
        value: "https://quay.io"
    target:
      kind: QuaySecretEngineConfig
  - patch: |-
      - op: replace
        path: /spec/namespaceName
        value: "redhat_na_ssa"
    target:
      kind: QuaySecretEngineRole