---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-config-operator 
  namespace: vault-config-operator 
spec:
  channel: <REPLACE>
  installPlanApproval: Automatic
  name: vault-config-operator 
  source: community-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    - name: VAULT_ADDR
      value: <vault-addr>
    - name: VAULT_SKIP_VERIFY
      value: "true"
    # when using custom CA certs
    # - name: VAULT_CACERT
    #   value: /vault-ca/ca.crt
    # - name: VAULT_TOKEN
    #   valueFrom:
    #     secretKeyRef:
    #       name: $JWT_SECRET
    #       key: token
    # volumes:
    # - name: vault-ca
    #   configMap:
    #     name: int-ca
    # volumeMounts:
    # - mountPath: /vault-ca
    #   name: vault-ca
