---
- name: Download tools
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    molecule_pip_dependencies:
      - kubernetes
  tasks:

    - name: Store user ENVs
      ansible.builtin.set_fact:
        molecule_user_home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
        molecule_user_path: "{{ lookup('ansible.builtin.env', 'PATH') }}"

    - name: Create local bin directory
      ansible.builtin.file:
        path: "{{ molecule_user_home_dir }}/bin"
        state: directory
        mode: '0770'
    
    - name: Download oc binary from OCP downloads svc endpoint
      ansible.builtin.get_url:
        url: http://downloads.openshift-console.svc.cluster.local/amd64/linux/oc
        dest: "{{ molecule_user_home_dir }}/bin/oc"
        mode: '0770'

    - name: Download helm binary from mirror.openshift.com
      ansible.builtin.get_url:
        url: https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/helm/3.12.1/helm-linux-amd64
        dest: "{{ molecule_user_home_dir }}/bin/helm"
        mode: '0770'
    
    - name: Add another bin dir to system-wide $PATH.
      ansible.builtin.lineinfile:
        path: "{{ molecule_user_home_dir }}/.bashrc"
        line: 'PATH=$PATH:{{ molecule_user_home_dir }}/bin'
        state: present

    - name: Ensure python dependencies are installed
      ansible.builtin.pip:
        name: "{{ molecule_pip_dependencies }}"
        state: present
      when: molecule_pip_dependencies is defined
