- name: DevHub infra setup
  hosts: localhost
  gather_facts: false
  vars:
    setup_rhsso: false
    idp_instance_name: "rhdh"
    git_system: "github"
    gitlab_instance_name: "gitlab"
    github_application_id: "{{ lookup('ansible.builtin.env', 'GITHUB_APP_ID') }}"
    gitlab_root_secret_name: "{{ gitlab_instance_name }}-gitlab-initial-root-password"
    quay_registry_server_url: "https://quay.io"
    ocp4_workload_redhat_developer_hub_gitlab_namespace: "gitlab-system"
    ocp4_workload_redhat_developer_hub_vault_namespace: "vault"
    ocp4_workload_redhat_developer_hub_backstage_namespace: "rhdh"
    ocp4_workload_redhat_developer_hub_gitlab_host: ""
    ocp4_workload_redhat_developer_hub_keycloak_host: ""
    ocp4_workload_redhat_developer_hub_backstage_gitops_repo: "https://github.com/redhat-na-ssa/redhat-developer-hub-gitops-bootstrap.git"

  tasks:
    - name: Retrieve Ingress config
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Ingress
        name: cluster
      register: r_ingress_config

    - name: Set OpenShift Cluster Domain
      ansible.builtin.set_fact:
        ocp4_workload_redhat_developer_hub_apps_domain: "{{ r_ingress_config.resources[0].spec.domain }}"

    - name: Set OpenShift Apps URLs
      ansible.builtin.set_fact:
        ocp4_workload_redhat_developer_hub_gitlab_host: "gitlab.gitlab-{{
          ocp4_workload_redhat_developer_hub_gitlab_namespace }}.{{
          ocp4_workload_redhat_developer_hub_apps_domain }}"
        ocp4_workload_redhat_developer_hub_keycloak_host: "keycloak-{{
          ocp4_workload_redhat_developer_hub_backstage_namespace }}.{{
          ocp4_workload_redhat_developer_hub_apps_domain }}"
        ocp4_workload_redhat_developer_hub_backstage_host: "backstage-{{
          ocp4_workload_redhat_developer_hub_backstage_namespace }}.{{
          ocp4_workload_redhat_developer_hub_apps_domain }}"
        ocp4_workload_redhat_developer_hub_devspaces_host: "devspaces.{{
          ocp4_workload_redhat_developer_hub_apps_domain }}"
        ocp4_workload_redhat_developer_hub_openshift_redirect_host: "oauth-openshift.{{
          ocp4_workload_redhat_developer_hub_apps_domain }}"
        ocp4_workload_redhat_developer_hub_openshift_console_host: console-openshift-console.{{
          ocp4_workload_redhat_developer_hub_apps_domain }}
        ocp4_workload_redhat_developer_hub_quay_host: "quay.io"

    - name: Debug vars
      ansible.builtin.debug:
        msg:
          - "ocp4_workload_redhat_developer_hub_apps_domain: {{ ocp4_workload_redhat_developer_hub_apps_domain }}"
          - "ocp4_workload_redhat_developer_hub_gitlab_host: {{ ocp4_workload_redhat_developer_hub_gitlab_host }}"
          - "ocp4_workload_redhat_developer_hub_keycloak_host: {{ ocp4_workload_redhat_developer_hub_keycloak_host }}"
          - "ocp4_workload_redhat_developer_hub_backstage_host: {{ ocp4_workload_redhat_developer_hub_backstage_host }}"
          - "ocp4_workload_redhat_developer_hub_devspaces_host: {{ ocp4_workload_redhat_developer_hub_devspaces_host }}"
          - "ocp4_workload_redhat_developer_hub_openshift_redirect_host: {{ ocp4_workload_redhat_developer_hub_openshift_redirect_host }}"
          - "ocp4_workload_redhat_developer_hub_openshift_console_host: {{ ocp4_workload_redhat_developer_hub_openshift_console_host }}"
          - "ocp4_workload_redhat_developer_hub_quay_host: {{ ocp4_workload_redhat_developer_hub_quay_host }}"

    - name: Setup Vault
      ansible.builtin.include_tasks:
        file: ./setup_vault.yml

    - name: Setup Gitlab dependencies
      ansible.builtin.include_tasks:
        file: ./setup_gitlab.yml
      when: git_system == "gitlab"

    # - name: Setup Gitlab repo dependencies
    #   include_tasks:
    #     file: ./setup_templates.yml
    #   loop: "{{ ocp4_workload_redhat_developer_hub_gitlab_template_locations }}"
    #   loop_control:
    #     loop_var: location

    - name: Setup RHSSO dependencies
      ansible.builtin.include_tasks:
        file: ./setup_rhsso.yml
      when: setup_rhsso is true
