apiVersion: v1
kind: Secret
metadata:
  name: rhdh-github-plugin-secret
  namespace: "{{ idp_namespace }}"
type: Opaque
data:
  GITHUB_APP_APP_ID: "{{ github_app_app_id | b64encode }}"
  GITHUB_APP_CLIENT_ID: "{{ github_app_client_id | b64encode }}"
  GITHUB_APP_CLIENT_SECRET: "{{ github_app_client_secret | b64encode }}"
  GITHUB_APP_PRIVATE_KEY: "{{ github_app_private_key | b64encode }}"
  GITHUB_APP_WEBHOOK_URL: "{{ github_app_webhook_url | b64encode }}"
  GITHUB_APP_WEBHOOK_SECRET: "{{ github_app_webhook_secret | b64encode }}"
  GITHUB_URL: "{{ github_url | b64encode }}"
  GITHUB_ORG: "{{ github_org | b64encode }}"