kind: Secret
apiVersion: v1
metadata:
  name: rhdh-argocd-plugin-secret
  namespace: "{{ idp_namespace }}"
data:
  ARGOCD_INSTANCE_NAME: "{{ argocd_instance_name | b64encode }}"
  ARGOCD_INSTANCE_URL: "{{ argocd_route_url | b64encode }}"
  ARGOCD_ADMIN_USERNAME: "{{ argocd_admin_username | b64encode }}"
  ARGOCD_ADMIN_PASSWORD: "{{ argocd_admin_password | b64encode }}"
type: Opaque