kind: Secret
apiVersion: v1
metadata:
  name: rhdh-quay-plugin-secret
  namespace: "{{ idp_namespace }}"
stringData:
  QUAY_URL: "{{ quay_registry_server_url }}"
  QUAY_BEARER_TOKEN: "{{ quay_token }}"
