kind: Secret
apiVersion: v1
metadata:
  name: rhdh-k8s-plugin-secret
  namespace: "{{ idp_namespace }}"
stringData:
  K8S_CLUSTER_NAME: "development-cluster"
  K8S_CLUSTER_TOKEN: "{{ k8s_plugin_sa_token }}"
  K8S_CLUSTER_URL: "{{ cluster_api_url }}"
