kind: Secret
apiVersion: v1
metadata:
  #intentionally using the same name as the original, so ansible will just update with new keys
  name: "rhdh-k8s-plugin-secret"
  namespace: "{{ idp_namespace }}"
stringData:
  {{ external_cluster_name | upper }}_K8S_CLUSTER_NAME: "{{ external_cluster_name | lower }}-cluster"
  {{ external_cluster_name | upper }}_K8S_CLUSTER_TOKEN: "{{ external_k8s_sa_token }}"
  {{ external_cluster_name | upper }}_K8S_CLUSTER_URL: "{{ external_cluster_api_url }}"
