- name: Vault Config setup
  hosts: localhost
  gather_facts: false
  vars:
    idp_namespace: "rhdh"
    idp_instance_name: "rhdh"
    rhdh_helm_chart_version: "0.2.0"
    git_system: "github"
    github_application_id: "{{ lookup('ansible.builtin.env', 'GITHUB_APP_APP_ID') }}"
    quay_registry_server_url: "https://quay.io"
    vault_namespace: "vault"
    vault_cluster_name: "dev-cluster"

  tasks:
    - name: Retrieve Ingress config
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        
        kind: Ingress
        name: cluster
      register: r_ingress_config

    - name: Retrieve Infrastructure config
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: r_infra_config

    - name: Set OpenShift Cluster Domain and API URLs
      ansible.builtin.set_fact:
        apps_cluster_domain: "{{ r_ingress_config.resources[0].spec.domain }}"
        cluster_api_url: "{{ r_infra_config.resources[0].status.apiServerURL }}"

    - name: Debug vars
      ansible.builtin.debug:
        msg:
          - "apps_cluster_domain: {{ apps_cluster_domain }}"
          - "cluster_api_url: {{ cluster_api_url }}"

    - name: Setup Vault
      ansible.builtin.include_tasks:
        file: ./setup_vault.yml
